# Created with package:mono_repo v2.5.0
language: dart

# Custom configuration
addons:
  chrome: stable
env:
  global: FORCE_TEST_EXIT=true

jobs:
  include:
    - stage: mono_repo_self_validate
      name: mono_repo self validate
      os: linux
      script: tool/mono_repo_self_validate.sh
    - stage: analyze_and_format
      name: "SDK: dev; PKGS: pkgs/test, pkgs/test_api, pkgs/test_core; TASKS: [`dartfmt -n --set-exit-if-changed .`, `dartanalyzer --enable-experiment=non-nullable --fatal-infos --fatal-warnings .`]"
      dart: dev
      os: linux
      env: PKGS="pkgs/test pkgs/test_api pkgs/test_core"
      script: tool/travis.sh dartfmt dartanalyzer
      script: ./tool/travis.sh command_4

stages:
  - unit_test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
